# Generated by Django 5.0.4 on 2025-12-08 10:45

import django.db.models.deletion
import notifications.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('conversation_type', models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group Chat'), ('channel', 'Channel')], default='direct', max_length=20)),
                ('created_by', models.UUIDField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('sender_id', models.UUIDField()),
                ('message_type', models.CharField(choices=[('text', 'TEXT'), ('emoji', 'EMOJI'), ('file', 'FILE'), ('image', 'IMAGE'), ('system', 'SYSTEM')], default='text', max_length=10)),
                ('content', models.TextField()),
                ('file_url', models.URLField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField()),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('device_type', models.CharField(choices=[('android', 'ANDROID'), ('ios', 'IOS'), ('web', 'WEB')], max_length=10)),
                ('device_token', models.CharField(max_length=500, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField()),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PushAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('notification_id', models.UUIDField()),
                ('device_token_id', models.UUIDField()),
                ('fcm_message_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sent', 'SENT'), ('delivered', 'DELIVERED'), ('opened', 'OPENED'), ('failed', 'FAILED')], max_length=10)),
                ('platform', models.CharField(choices=[('android', 'ANDROID'), ('ios', 'IOS'), ('web', 'WEB')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('notification_id', models.UUIDField()),
                ('twilio_sid', models.CharField(max_length=255, unique=True)),
                ('recipient', models.CharField(max_length=20)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('segments', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('price_unit', models.CharField(default='USD', max_length=10)),
                ('error_code', models.CharField(blank=True, max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypingIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='notificatio_tenant__91c5ba_idx',
            old_name='notifications_audit_tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='campaign',
            new_name='notificatio_tenant__92e512_idx',
            old_name='notifications_campaign_tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='notificationrecord',
            new_name='notificatio_tenant__a92477_idx',
            old_name='notifications_notif_tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='notificationrecord',
            new_name='notificatio_tenant__2620f7_idx',
            old_name='notifications_notif_tenant_2idx',
        ),
        migrations.RenameIndex(
            model_name='notificationrecord',
            new_name='notificatio_status_98916c_idx',
            old_name='notifications_notif_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationtemplate',
            new_name='notificatio_tenant__3c7133_idx',
            old_name='notifications_not_tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='tenantcredentials',
            new_name='notificatio_tenant__1d7367_idx',
            old_name='notifications_ten_tenant__idx',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='content',
            field=models.JSONField(blank=True, null=True, validators=[notifications.models.validate_template_content]),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='content',
            field=models.JSONField(validators=[notifications.models.validate_template_content]),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['tenant_id', 'conversation_type'], name='notificatio_tenant__0ef9ad_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['tenant_id', 'last_message_at'], name='notificatio_tenant__2cf0bd_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['created_by'], name='notificatio_created_97a04a_idx'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notifications.chatconversation'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='notifications.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='notifications.chatconversation'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['tenant_id', 'user_id'], name='notificatio_tenant__915626_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['device_token'], name='notificatio_device__7b08eb_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['is_active', 'last_used'], name='notificatio_is_acti_419362_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicetoken',
            unique_together={('user_id', 'device_id')},
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='notifications.chatmessage'),
        ),
        migrations.AddIndex(
            model_name='pushanalytics',
            index=models.Index(fields=['tenant_id', 'notification_id'], name='notificatio_tenant__045fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='pushanalytics',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_9e6ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='pushanalytics',
            index=models.Index(fields=['platform', 'status'], name='notificatio_platfor_72e921_idx'),
        ),
        migrations.AddIndex(
            model_name='smsanalytics',
            index=models.Index(fields=['tenant_id', 'notification_id'], name='notificatio_tenant__6b32a2_idx'),
        ),
        migrations.AddIndex(
            model_name='smsanalytics',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_f707a1_idx'),
        ),
        migrations.AddIndex(
            model_name='smsanalytics',
            index=models.Index(fields=['twilio_sid'], name='notificatio_twilio__d0355e_idx'),
        ),
        migrations.AddIndex(
            model_name='smsanalytics',
            index=models.Index(fields=['recipient', 'status'], name='notificatio_recipie_f18bf6_idx'),
        ),
        migrations.AddField(
            model_name='typingindicator',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.chatconversation'),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='current_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.chatconversation'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['tenant_id', 'conversation', 'created_at'], name='notificatio_tenant__d82593_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'is_deleted'], name='notificatio_convers_5080d2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender_id', 'created_at'], name='notificatio_sender__f76ea5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['tenant_id', 'user_id'], name='notificatio_tenant__844441_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['conversation', 'is_active'], name='notificatio_convers_f1a60f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user_id', 'last_seen_at'], name='notificatio_user_id_fd6cef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('conversation', 'user_id')},
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['tenant_id', 'message'], name='notificatio_tenant__ceef27_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['user_id', 'created_at'], name='notificatio_user_id_a5a0cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user_id', 'emoji')},
        ),
        migrations.AddIndex(
            model_name='typingindicator',
            index=models.Index(fields=['tenant_id', 'conversation'], name='notificatio_tenant__857205_idx'),
        ),
        migrations.AddIndex(
            model_name='typingindicator',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_2552e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typingindicator',
            unique_together={('conversation', 'user_id')},
        ),
        migrations.AddIndex(
            model_name='userpresence',
            index=models.Index(fields=['tenant_id', 'status'], name='notificatio_tenant__592142_idx'),
        ),
        migrations.AddIndex(
            model_name='userpresence',
            index=models.Index(fields=['user_id'], name='notificatio_user_id_ccde7c_idx'),
        ),
    ]
