# Generated by Django 5.0.4 on 2025-12-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_chatconversation_chatmessage_chatparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcredentials',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
