# Generated by Django 5.0.4 on 2025-12-09 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_tenantcredentials_is_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('recipient', models.CharField(max_length=500)),
                ('message_type', models.CharField(default='inapp_notification', max_length=20)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('sent', 'SENT'), ('delivered', 'DELIVERED'), ('failed', 'FAILED')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inapp_message', to='notifications.notificationrecord')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'recipient', 'status'], name='notificatio_tenant__c8900e_idx'), models.Index(fields=['tenant_id', 'status', 'created_at'], name='notificatio_tenant__15f4de_idx'), models.Index(fields=['recipient', 'status'], name='notificatio_recipie_4c6000_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_263a9a_idx')],
            },
        ),
    ]
